// Generated by gencpp from file cruiser_msgs/behaviours.msg
// DO NOT EDIT!


#ifndef CRUISER_MSGS_MESSAGE_BEHAVIOURS_H
#define CRUISER_MSGS_MESSAGE_BEHAVIOURS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cruiser_msgs
{
template <class ContainerAllocator>
struct behaviours_
{
  typedef behaviours_<ContainerAllocator> Type;

  behaviours_()
    : header()
    , datapacket()
    , clientFd(0)  {
    }
  behaviours_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , datapacket(_alloc)
    , clientFd(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _datapacket_type;
  _datapacket_type datapacket;

   typedef uint32_t _clientFd_type;
  _clientFd_type clientFd;





  typedef boost::shared_ptr< ::cruiser_msgs::behaviours_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cruiser_msgs::behaviours_<ContainerAllocator> const> ConstPtr;

}; // struct behaviours_

typedef ::cruiser_msgs::behaviours_<std::allocator<void> > behaviours;

typedef boost::shared_ptr< ::cruiser_msgs::behaviours > behavioursPtr;
typedef boost::shared_ptr< ::cruiser_msgs::behaviours const> behavioursConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cruiser_msgs::behaviours_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cruiser_msgs::behaviours_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cruiser_msgs::behaviours_<ContainerAllocator1> & lhs, const ::cruiser_msgs::behaviours_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.datapacket == rhs.datapacket &&
    lhs.clientFd == rhs.clientFd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cruiser_msgs::behaviours_<ContainerAllocator1> & lhs, const ::cruiser_msgs::behaviours_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cruiser_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cruiser_msgs::behaviours_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cruiser_msgs::behaviours_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cruiser_msgs::behaviours_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cruiser_msgs::behaviours_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cruiser_msgs::behaviours_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cruiser_msgs::behaviours_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cruiser_msgs::behaviours_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1fa06883f2e6627b210d8fd6b7397ec6";
  }

  static const char* value(const ::cruiser_msgs::behaviours_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1fa06883f2e6627bULL;
  static const uint64_t static_value2 = 0x210d8fd6b7397ec6ULL;
};

template<class ContainerAllocator>
struct DataType< ::cruiser_msgs::behaviours_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cruiser_msgs/behaviours";
  }

  static const char* value(const ::cruiser_msgs::behaviours_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cruiser_msgs::behaviours_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"#command packet\n"
"string datapacket\n"
"\n"
"#communication client\n"
"uint32 clientFd\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::cruiser_msgs::behaviours_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cruiser_msgs::behaviours_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.datapacket);
      stream.next(m.clientFd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct behaviours_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cruiser_msgs::behaviours_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cruiser_msgs::behaviours_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "datapacket: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.datapacket);
    s << indent << "clientFd: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.clientFd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRUISER_MSGS_MESSAGE_BEHAVIOURS_H
