// Generated by gencpp from file cruiser_msgs/ClearUwbAnchorRequest.msg
// DO NOT EDIT!


#ifndef CRUISER_MSGS_MESSAGE_CLEARUWBANCHORREQUEST_H
#define CRUISER_MSGS_MESSAGE_CLEARUWBANCHORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cruiser_msgs
{
template <class ContainerAllocator>
struct ClearUwbAnchorRequest_
{
  typedef ClearUwbAnchorRequest_<ContainerAllocator> Type;

  ClearUwbAnchorRequest_()
    {
    }
  ClearUwbAnchorRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::cruiser_msgs::ClearUwbAnchorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cruiser_msgs::ClearUwbAnchorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ClearUwbAnchorRequest_

typedef ::cruiser_msgs::ClearUwbAnchorRequest_<std::allocator<void> > ClearUwbAnchorRequest;

typedef boost::shared_ptr< ::cruiser_msgs::ClearUwbAnchorRequest > ClearUwbAnchorRequestPtr;
typedef boost::shared_ptr< ::cruiser_msgs::ClearUwbAnchorRequest const> ClearUwbAnchorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cruiser_msgs::ClearUwbAnchorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cruiser_msgs::ClearUwbAnchorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace cruiser_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cruiser_msgs::ClearUwbAnchorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cruiser_msgs::ClearUwbAnchorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cruiser_msgs::ClearUwbAnchorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cruiser_msgs::ClearUwbAnchorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cruiser_msgs::ClearUwbAnchorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cruiser_msgs::ClearUwbAnchorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cruiser_msgs::ClearUwbAnchorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::cruiser_msgs::ClearUwbAnchorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::cruiser_msgs::ClearUwbAnchorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cruiser_msgs/ClearUwbAnchorRequest";
  }

  static const char* value(const ::cruiser_msgs::ClearUwbAnchorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cruiser_msgs::ClearUwbAnchorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
;
  }

  static const char* value(const ::cruiser_msgs::ClearUwbAnchorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cruiser_msgs::ClearUwbAnchorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClearUwbAnchorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cruiser_msgs::ClearUwbAnchorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::cruiser_msgs::ClearUwbAnchorRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CRUISER_MSGS_MESSAGE_CLEARUWBANCHORREQUEST_H
