// Generated by gencpp from file cruiser_msgs/CruiserBrakeCtl.msg
// DO NOT EDIT!


#ifndef CRUISER_MSGS_MESSAGE_CRUISERBRAKECTL_H
#define CRUISER_MSGS_MESSAGE_CRUISERBRAKECTL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cruiser_msgs
{
template <class ContainerAllocator>
struct CruiserBrakeCtl_
{
  typedef CruiserBrakeCtl_<ContainerAllocator> Type;

  CruiserBrakeCtl_()
    : brake(false)  {
    }
  CruiserBrakeCtl_(const ContainerAllocator& _alloc)
    : brake(false)  {
  (void)_alloc;
    }



   typedef uint8_t _brake_type;
  _brake_type brake;





  typedef boost::shared_ptr< ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator> const> ConstPtr;

}; // struct CruiserBrakeCtl_

typedef ::cruiser_msgs::CruiserBrakeCtl_<std::allocator<void> > CruiserBrakeCtl;

typedef boost::shared_ptr< ::cruiser_msgs::CruiserBrakeCtl > CruiserBrakeCtlPtr;
typedef boost::shared_ptr< ::cruiser_msgs::CruiserBrakeCtl const> CruiserBrakeCtlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator1> & lhs, const ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator2> & rhs)
{
  return lhs.brake == rhs.brake;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator1> & lhs, const ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cruiser_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "691501d2b5eb4dc01a97397d7baf5fba";
  }

  static const char* value(const ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x691501d2b5eb4dc0ULL;
  static const uint64_t static_value2 = 0x1a97397d7baf5fbaULL;
};

template<class ContainerAllocator>
struct DataType< ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cruiser_msgs/CruiserBrakeCtl";
  }

  static const char* value(const ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# cruiser brake control,topic name \"Cruiser_brake\"\n"
"# brake=1,brake cruiser\n"
"# brake=0,reset to normal\n"
"bool brake\n"
"\n"
;
  }

  static const char* value(const ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.brake);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CruiserBrakeCtl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cruiser_msgs::CruiserBrakeCtl_<ContainerAllocator>& v)
  {
    s << indent << "brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brake);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRUISER_MSGS_MESSAGE_CRUISERBRAKECTL_H
