// Generated by gencpp from file cruiser_msgs/GetMapJsonResponse.msg
// DO NOT EDIT!


#ifndef CRUISER_MSGS_MESSAGE_GETMAPJSONRESPONSE_H
#define CRUISER_MSGS_MESSAGE_GETMAPJSONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <cruiser_msgs/MapJson.h>

namespace cruiser_msgs
{
template <class ContainerAllocator>
struct GetMapJsonResponse_
{
  typedef GetMapJsonResponse_<ContainerAllocator> Type;

  GetMapJsonResponse_()
    : json()  {
    }
  GetMapJsonResponse_(const ContainerAllocator& _alloc)
    : json(_alloc)  {
  (void)_alloc;
    }



   typedef  ::cruiser_msgs::MapJson_<ContainerAllocator>  _json_type;
  _json_type json;





  typedef boost::shared_ptr< ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetMapJsonResponse_

typedef ::cruiser_msgs::GetMapJsonResponse_<std::allocator<void> > GetMapJsonResponse;

typedef boost::shared_ptr< ::cruiser_msgs::GetMapJsonResponse > GetMapJsonResponsePtr;
typedef boost::shared_ptr< ::cruiser_msgs::GetMapJsonResponse const> GetMapJsonResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator1> & lhs, const ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator2> & rhs)
{
  return lhs.json == rhs.json;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator1> & lhs, const ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cruiser_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6825166e7da48608dd55394f68c70e3e";
  }

  static const char* value(const ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6825166e7da48608ULL;
  static const uint64_t static_value2 = 0xdd55394f68c70e3eULL;
};

template<class ContainerAllocator>
struct DataType< ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cruiser_msgs/GetMapJsonResponse";
  }

  static const char* value(const ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cruiser_msgs/MapJson json\n"
"\n"
"\n"
"================================================================================\n"
"MSG: cruiser_msgs/MapJson\n"
"uint8[] data\n"
"\n"
;
  }

  static const char* value(const ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.json);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetMapJsonResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cruiser_msgs::GetMapJsonResponse_<ContainerAllocator>& v)
  {
    s << indent << "json: ";
    s << std::endl;
    Printer< ::cruiser_msgs::MapJson_<ContainerAllocator> >::stream(s, indent + "  ", v.json);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRUISER_MSGS_MESSAGE_GETMAPJSONRESPONSE_H
