// Generated by gencpp from file cruiser_msgs/MapJson.msg
// DO NOT EDIT!


#ifndef CRUISER_MSGS_MESSAGE_MAPJSON_H
#define CRUISER_MSGS_MESSAGE_MAPJSON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cruiser_msgs
{
template <class ContainerAllocator>
struct MapJson_
{
  typedef MapJson_<ContainerAllocator> Type;

  MapJson_()
    : data()  {
    }
  MapJson_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::cruiser_msgs::MapJson_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cruiser_msgs::MapJson_<ContainerAllocator> const> ConstPtr;

}; // struct MapJson_

typedef ::cruiser_msgs::MapJson_<std::allocator<void> > MapJson;

typedef boost::shared_ptr< ::cruiser_msgs::MapJson > MapJsonPtr;
typedef boost::shared_ptr< ::cruiser_msgs::MapJson const> MapJsonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cruiser_msgs::MapJson_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cruiser_msgs::MapJson_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cruiser_msgs::MapJson_<ContainerAllocator1> & lhs, const ::cruiser_msgs::MapJson_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cruiser_msgs::MapJson_<ContainerAllocator1> & lhs, const ::cruiser_msgs::MapJson_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cruiser_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cruiser_msgs::MapJson_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cruiser_msgs::MapJson_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cruiser_msgs::MapJson_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cruiser_msgs::MapJson_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cruiser_msgs::MapJson_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cruiser_msgs::MapJson_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cruiser_msgs::MapJson_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f43a8e1b362b75baa741461b46adc7e0";
  }

  static const char* value(const ::cruiser_msgs::MapJson_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf43a8e1b362b75baULL;
  static const uint64_t static_value2 = 0xa741461b46adc7e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::cruiser_msgs::MapJson_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cruiser_msgs/MapJson";
  }

  static const char* value(const ::cruiser_msgs::MapJson_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cruiser_msgs::MapJson_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] data\n"
"\n"
;
  }

  static const char* value(const ::cruiser_msgs::MapJson_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cruiser_msgs::MapJson_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapJson_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cruiser_msgs::MapJson_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cruiser_msgs::MapJson_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRUISER_MSGS_MESSAGE_MAPJSON_H
