// Generated by gencpp from file cruiser_msgs/SetUwbAnchor.msg
// DO NOT EDIT!


#ifndef CRUISER_MSGS_MESSAGE_SETUWBANCHOR_H
#define CRUISER_MSGS_MESSAGE_SETUWBANCHOR_H

#include <ros/service_traits.h>


#include <cruiser_msgs/SetUwbAnchorRequest.h>
#include <cruiser_msgs/SetUwbAnchorResponse.h>


namespace cruiser_msgs
{

struct SetUwbAnchor
{

typedef SetUwbAnchorRequest Request;
typedef SetUwbAnchorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetUwbAnchor
} // namespace cruiser_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cruiser_msgs::SetUwbAnchor > {
  static const char* value()
  {
    return "99557491fedf4df60949814ebddfa650";
  }

  static const char* value(const ::cruiser_msgs::SetUwbAnchor&) { return value(); }
};

template<>
struct DataType< ::cruiser_msgs::SetUwbAnchor > {
  static const char* value()
  {
    return "cruiser_msgs/SetUwbAnchor";
  }

  static const char* value(const ::cruiser_msgs::SetUwbAnchor&) { return value(); }
};


// service_traits::MD5Sum< ::cruiser_msgs::SetUwbAnchorRequest> should match
// service_traits::MD5Sum< ::cruiser_msgs::SetUwbAnchor >
template<>
struct MD5Sum< ::cruiser_msgs::SetUwbAnchorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cruiser_msgs::SetUwbAnchor >::value();
  }
  static const char* value(const ::cruiser_msgs::SetUwbAnchorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cruiser_msgs::SetUwbAnchorRequest> should match
// service_traits::DataType< ::cruiser_msgs::SetUwbAnchor >
template<>
struct DataType< ::cruiser_msgs::SetUwbAnchorRequest>
{
  static const char* value()
  {
    return DataType< ::cruiser_msgs::SetUwbAnchor >::value();
  }
  static const char* value(const ::cruiser_msgs::SetUwbAnchorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cruiser_msgs::SetUwbAnchorResponse> should match
// service_traits::MD5Sum< ::cruiser_msgs::SetUwbAnchor >
template<>
struct MD5Sum< ::cruiser_msgs::SetUwbAnchorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cruiser_msgs::SetUwbAnchor >::value();
  }
  static const char* value(const ::cruiser_msgs::SetUwbAnchorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cruiser_msgs::SetUwbAnchorResponse> should match
// service_traits::DataType< ::cruiser_msgs::SetUwbAnchor >
template<>
struct DataType< ::cruiser_msgs::SetUwbAnchorResponse>
{
  static const char* value()
  {
    return DataType< ::cruiser_msgs::SetUwbAnchor >::value();
  }
  static const char* value(const ::cruiser_msgs::SetUwbAnchorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRUISER_MSGS_MESSAGE_SETUWBANCHOR_H
