// Generated by gencpp from file cruiser_msgs/uwbCoordinateMapResponse.msg
// DO NOT EDIT!


#ifndef CRUISER_MSGS_MESSAGE_UWBCOORDINATEMAPRESPONSE_H
#define CRUISER_MSGS_MESSAGE_UWBCOORDINATEMAPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cruiser_msgs
{
template <class ContainerAllocator>
struct uwbCoordinateMapResponse_
{
  typedef uwbCoordinateMapResponse_<ContainerAllocator> Type;

  uwbCoordinateMapResponse_()
    : result(0)
    , output_x(0.0)
    , output_y(0.0)
    , output_theta(0.0)  {
    }
  uwbCoordinateMapResponse_(const ContainerAllocator& _alloc)
    : result(0)
    , output_x(0.0)
    , output_y(0.0)
    , output_theta(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _result_type;
  _result_type result;

   typedef float _output_x_type;
  _output_x_type output_x;

   typedef float _output_y_type;
  _output_y_type output_y;

   typedef float _output_theta_type;
  _output_theta_type output_theta;





  typedef boost::shared_ptr< ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct uwbCoordinateMapResponse_

typedef ::cruiser_msgs::uwbCoordinateMapResponse_<std::allocator<void> > uwbCoordinateMapResponse;

typedef boost::shared_ptr< ::cruiser_msgs::uwbCoordinateMapResponse > uwbCoordinateMapResponsePtr;
typedef boost::shared_ptr< ::cruiser_msgs::uwbCoordinateMapResponse const> uwbCoordinateMapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator1> & lhs, const ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.output_x == rhs.output_x &&
    lhs.output_y == rhs.output_y &&
    lhs.output_theta == rhs.output_theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator1> & lhs, const ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cruiser_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b33e9bd7010c42d2771bcf6ee2749245";
  }

  static const char* value(const ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb33e9bd7010c42d2ULL;
  static const uint64_t static_value2 = 0x771bcf6ee2749245ULL;
};

template<class ContainerAllocator>
struct DataType< ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cruiser_msgs/uwbCoordinateMapResponse";
  }

  static const char* value(const ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 result\n"
"float32 output_x\n"
"float32 output_y\n"
"float32 output_theta\n"
"\n"
"\n"
;
  }

  static const char* value(const ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.output_x);
      stream.next(m.output_y);
      stream.next(m.output_theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct uwbCoordinateMapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cruiser_msgs::uwbCoordinateMapResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.result);
    s << indent << "output_x: ";
    Printer<float>::stream(s, indent + "  ", v.output_x);
    s << indent << "output_y: ";
    Printer<float>::stream(s, indent + "  ", v.output_y);
    s << indent << "output_theta: ";
    Printer<float>::stream(s, indent + "  ", v.output_theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRUISER_MSGS_MESSAGE_UWBCOORDINATEMAPRESPONSE_H
