# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cruiser_msgs/joint_abnor.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class joint_abnor(genpy.Message):
  _md5sum = "d33fc6a742571f80a3793eed68aa9c0d"
  _type = "cruiser_msgs/joint_abnor"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string jointName

# Joints index
int32 jointIndex

# abnorState
# 1:low Temperature protection
# 2:high Temperature protection
# 3:low voltage portection
# 4:high voltage portection
# 5:current portection
# 6:force portection
# 7:fuse portection
# 8:PWM portection
int32 abnorState
"""
  __slots__ = ['jointName','jointIndex','abnorState']
  _slot_types = ['string','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       jointName,jointIndex,abnorState

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(joint_abnor, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.jointName is None:
        self.jointName = ''
      if self.jointIndex is None:
        self.jointIndex = 0
      if self.abnorState is None:
        self.abnorState = 0
    else:
      self.jointName = ''
      self.jointIndex = 0
      self.abnorState = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.jointName
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2i().pack(_x.jointIndex, _x.abnorState))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.jointName = str[start:end].decode('utf-8')
      else:
        self.jointName = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.jointIndex, _x.abnorState,) = _get_struct_2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.jointName
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2i().pack(_x.jointIndex, _x.abnorState))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.jointName = str[start:end].decode('utf-8')
      else:
        self.jointName = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.jointIndex, _x.abnorState,) = _get_struct_2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i = None
def _get_struct_2i():
    global _struct_2i
    if _struct_2i is None:
        _struct_2i = struct.Struct("<2i")
    return _struct_2i
