// Generated by gencpp from file ces_task/TaskHmiCtrlResponse.msg
// DO NOT EDIT!


#ifndef CES_TASK_MESSAGE_TASKHMICTRLRESPONSE_H
#define CES_TASK_MESSAGE_TASKHMICTRLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ces_task
{
template <class ContainerAllocator>
struct TaskHmiCtrlResponse_
{
  typedef TaskHmiCtrlResponse_<ContainerAllocator> Type;

  TaskHmiCtrlResponse_()
    : success(false)
    , message()  {
    }
  TaskHmiCtrlResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::ces_task::TaskHmiCtrlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ces_task::TaskHmiCtrlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TaskHmiCtrlResponse_

typedef ::ces_task::TaskHmiCtrlResponse_<std::allocator<void> > TaskHmiCtrlResponse;

typedef boost::shared_ptr< ::ces_task::TaskHmiCtrlResponse > TaskHmiCtrlResponsePtr;
typedef boost::shared_ptr< ::ces_task::TaskHmiCtrlResponse const> TaskHmiCtrlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ces_task::TaskHmiCtrlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ces_task::TaskHmiCtrlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ces_task

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ces_task': ['/home/cjl/core_ws/walker_ws/walker2_motion_output/src/ces_task/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ces_task::TaskHmiCtrlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ces_task::TaskHmiCtrlResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ces_task::TaskHmiCtrlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ces_task::TaskHmiCtrlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ces_task::TaskHmiCtrlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ces_task::TaskHmiCtrlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ces_task::TaskHmiCtrlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::ces_task::TaskHmiCtrlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::ces_task::TaskHmiCtrlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ces_task/TaskHmiCtrlResponse";
  }

  static const char* value(const ::ces_task::TaskHmiCtrlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ces_task::TaskHmiCtrlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
bool success\n\
\n\
\n\
string message\n\
\n\
\n\
";
  }

  static const char* value(const ::ces_task::TaskHmiCtrlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ces_task::TaskHmiCtrlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskHmiCtrlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ces_task::TaskHmiCtrlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ces_task::TaskHmiCtrlResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CES_TASK_MESSAGE_TASKHMICTRLRESPONSE_H
