int32 TRIGGER_RELOCALIZITION =0
int32 GET_STATUS =1
int32 data
---
int32 STATE_IDLE =0
int32 STATE_ESTMATING =1
int32 STATE_SUCCESS = 2
int32 STATE_FAIL = 3
int32 TRIGGER_SUCCESS = 4
int32 status

