// Generated by gencpp from file cruiser_msgs/ChassisCommandRequest.msg
// DO NOT EDIT!


#ifndef CRUISER_MSGS_MESSAGE_CHASSISCOMMANDREQUEST_H
#define CRUISER_MSGS_MESSAGE_CHASSISCOMMANDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cruiser_msgs
{
template <class ContainerAllocator>
struct ChassisCommandRequest_
{
  typedef ChassisCommandRequest_<ContainerAllocator> Type;

  ChassisCommandRequest_()
    : command()
    , x(0.0)
    , y(0.0)
    , angle(0.0)  {
    }
  ChassisCommandRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)
    , x(0.0)
    , y(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::cruiser_msgs::ChassisCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cruiser_msgs::ChassisCommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ChassisCommandRequest_

typedef ::cruiser_msgs::ChassisCommandRequest_<std::allocator<void> > ChassisCommandRequest;

typedef boost::shared_ptr< ::cruiser_msgs::ChassisCommandRequest > ChassisCommandRequestPtr;
typedef boost::shared_ptr< ::cruiser_msgs::ChassisCommandRequest const> ChassisCommandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cruiser_msgs::ChassisCommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cruiser_msgs::ChassisCommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cruiser_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'cruiser_msgs': ['/home/cjl/core_ws/walker_ws/walker2_motion_output/src/ros_common/cruiser_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cruiser_msgs::ChassisCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cruiser_msgs::ChassisCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cruiser_msgs::ChassisCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cruiser_msgs::ChassisCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cruiser_msgs::ChassisCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cruiser_msgs::ChassisCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cruiser_msgs::ChassisCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd31140473c3b1e0c7396ddf3cddef8f";
  }

  static const char* value(const ::cruiser_msgs::ChassisCommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd31140473c3b1e0ULL;
  static const uint64_t static_value2 = 0xc7396ddf3cddef8fULL;
};

template<class ContainerAllocator>
struct DataType< ::cruiser_msgs::ChassisCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cruiser_msgs/ChassisCommandRequest";
  }

  static const char* value(const ::cruiser_msgs::ChassisCommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cruiser_msgs::ChassisCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n\
float64 x\n\
float64 y\n\
float64 angle\n\
";
  }

  static const char* value(const ::cruiser_msgs::ChassisCommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cruiser_msgs::ChassisCommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChassisCommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cruiser_msgs::ChassisCommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cruiser_msgs::ChassisCommandRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRUISER_MSGS_MESSAGE_CHASSISCOMMANDREQUEST_H
