(cl:defpackage walker_srvs-srv
  (:use )
  (:export
   "LEG_MOTION_METAFUNCCTRL"
   "<LEG_MOTION_METAFUNCCTRL-REQUEST>"
   "LEG_MOTION_METAFUNCCTRL-REQUEST"
   "<LEG_MOTION_METAFUNCCTRL-RESPONSE>"
   "LEG_MOTION_METAFUNCCTRL-RESPONSE"
  ))

