// Generated by gencpp from file logger/configureResponse.msg
// DO NOT EDIT!


#ifndef LOGGER_MESSAGE_CONFIGURERESPONSE_H
#define LOGGER_MESSAGE_CONFIGURERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace logger
{
template <class ContainerAllocator>
struct configureResponse_
{
  typedef configureResponse_<ContainerAllocator> Type;

  configureResponse_()
    : capacity(0)
    , path()
    , result(false)  {
    }
  configureResponse_(const ContainerAllocator& _alloc)
    : capacity(0)
    , path(_alloc)
    , result(false)  {
  (void)_alloc;
    }



   typedef int32_t _capacity_type;
  _capacity_type capacity;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _path_type;
  _path_type path;

   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::logger::configureResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::logger::configureResponse_<ContainerAllocator> const> ConstPtr;

}; // struct configureResponse_

typedef ::logger::configureResponse_<std::allocator<void> > configureResponse;

typedef boost::shared_ptr< ::logger::configureResponse > configureResponsePtr;
typedef boost::shared_ptr< ::logger::configureResponse const> configureResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::logger::configureResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::logger::configureResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::logger::configureResponse_<ContainerAllocator1> & lhs, const ::logger::configureResponse_<ContainerAllocator2> & rhs)
{
  return lhs.capacity == rhs.capacity &&
    lhs.path == rhs.path &&
    lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::logger::configureResponse_<ContainerAllocator1> & lhs, const ::logger::configureResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace logger

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::logger::configureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::logger::configureResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::logger::configureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::logger::configureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::logger::configureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::logger::configureResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::logger::configureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec415df144abfdbc57a28b2b48f42288";
  }

  static const char* value(const ::logger::configureResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec415df144abfdbcULL;
  static const uint64_t static_value2 = 0x57a28b2b48f42288ULL;
};

template<class ContainerAllocator>
struct DataType< ::logger::configureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "logger/configureResponse";
  }

  static const char* value(const ::logger::configureResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::logger::configureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int32 capacity\n"
"\n"
"string path\n"
"bool result\n"
"\n"
;
  }

  static const char* value(const ::logger::configureResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::logger::configureResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.capacity);
      stream.next(m.path);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct configureResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::logger::configureResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::logger::configureResponse_<ContainerAllocator>& v)
  {
    s << indent << "capacity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.capacity);
    s << indent << "path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.path);
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOGGER_MESSAGE_CONFIGURERESPONSE_H
