# current task id, defined in 'TaskLegStatus.msg'
string task_id

# who send request
string demander

# who execute task
string executor

# command: start or stop
string CMD_START=start
string CMD_STOP=stop
string cmd

---

# who reply response
string owner

# indicate status
bool success

# informational, e.g. for error messages
string message
