#mode对应的常量
string MODE_QUERY=query
string MODE_SET_CAPACITY=set_capacity
string MODE_SET_PATH=set_path

string node
#set or query,设置或查询
string mode
#容量，以条数为单位
int32 capacity
#数据存放路径
string path
---
#查询容量，以条数为单位
int32 capacity
#查询数据存放路径
string path
bool result
