// Generated by gencpp from file walker_arm/TaskService.msg
// DO NOT EDIT!


#ifndef WALKER_ARM_MESSAGE_TASKSERVICE_H
#define WALKER_ARM_MESSAGE_TASKSERVICE_H

#include <ros/service_traits.h>


#include <walker_arm/TaskServiceRequest.h>
#include <walker_arm/TaskServiceResponse.h>


namespace walker_arm
{

struct TaskService
{

typedef TaskServiceRequest Request;
typedef TaskServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TaskService
} // namespace walker_arm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::walker_arm::TaskService > {
  static const char* value()
  {
    return "4fad11411fd801536b613979f3a27f21";
  }

  static const char* value(const ::walker_arm::TaskService&) { return value(); }
};

template<>
struct DataType< ::walker_arm::TaskService > {
  static const char* value()
  {
    return "walker_arm/TaskService";
  }

  static const char* value(const ::walker_arm::TaskService&) { return value(); }
};


// service_traits::MD5Sum< ::walker_arm::TaskServiceRequest> should match
// service_traits::MD5Sum< ::walker_arm::TaskService >
template<>
struct MD5Sum< ::walker_arm::TaskServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::walker_arm::TaskService >::value();
  }
  static const char* value(const ::walker_arm::TaskServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::walker_arm::TaskServiceRequest> should match
// service_traits::DataType< ::walker_arm::TaskService >
template<>
struct DataType< ::walker_arm::TaskServiceRequest>
{
  static const char* value()
  {
    return DataType< ::walker_arm::TaskService >::value();
  }
  static const char* value(const ::walker_arm::TaskServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::walker_arm::TaskServiceResponse> should match
// service_traits::MD5Sum< ::walker_arm::TaskService >
template<>
struct MD5Sum< ::walker_arm::TaskServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::walker_arm::TaskService >::value();
  }
  static const char* value(const ::walker_arm::TaskServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::walker_arm::TaskServiceResponse> should match
// service_traits::DataType< ::walker_arm::TaskService >
template<>
struct DataType< ::walker_arm::TaskServiceResponse>
{
  static const char* value()
  {
    return DataType< ::walker_arm::TaskService >::value();
  }
  static const char* value(const ::walker_arm::TaskServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WALKER_ARM_MESSAGE_TASKSERVICE_H
