# legs status defines
string INIT=standInit
string STANDING=standing
string SCRIPTING=scripting
string NAV=navigating
string ARMCTRL=armCtrl
string VISIONCTRL=visionCtrl
string KEYBOARDCTRL=keyboardCtrl
string REMOTERCTRL=remoterCtrl
string BALANCE=balance
string TAIJI_INIT=taijiInit
string TAIJI=taiji
string YOGA_INIT=yogaInit
string YOGA=yoga
string EMSTOP=emergencyStop

##############################################
# current leg status
string status
