(cl:in-package cruiser_msgs-srv)
(cl:export '(CMD-VAL
          CMD
          YEAR-VAL
          YEAR
          MONTH-VAL
          MONTH
          DAY-VAL
          DAY
          HOUR-VAL
          HOUR
          MIN-VAL
          MIN
          SEC-VAL
          SEC
          TIMERENABLE-VAL
          TIMERENABLE
          FULLPOWERON-VAL
          FULLPOWERON
          FLAG-VAL
          FLAG
          YEAR-VAL
          YEAR
          MONTH-VAL
          MONTH
          DAY-VAL
          DAY
          HOUR-VAL
          HOUR
          MIN-VAL
          MIN
          SEC-VAL
          SEC
          MANUAL-VAL
          MANUAL
          ADAPTER-VAL
          ADAPTER
          STATION-VAL
          STATION
          TIMER-VAL
          TIMER
          STATE-VAL
          STATE
          SUCCESS-VAL
          SUCCESS
))