// Generated by gencpp from file servo_ctrl/EcatGetVer.msg
// DO NOT EDIT!


#ifndef SERVO_CTRL_MESSAGE_ECATGETVER_H
#define SERVO_CTRL_MESSAGE_ECATGETVER_H

#include <ros/service_traits.h>


#include <servo_ctrl/EcatGetVerRequest.h>
#include <servo_ctrl/EcatGetVerResponse.h>


namespace servo_ctrl
{

struct EcatGetVer
{

typedef EcatGetVerRequest Request;
typedef EcatGetVerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EcatGetVer
} // namespace servo_ctrl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::servo_ctrl::EcatGetVer > {
  static const char* value()
  {
    return "3f1b5b791580e357125da8eb47534614";
  }

  static const char* value(const ::servo_ctrl::EcatGetVer&) { return value(); }
};

template<>
struct DataType< ::servo_ctrl::EcatGetVer > {
  static const char* value()
  {
    return "servo_ctrl/EcatGetVer";
  }

  static const char* value(const ::servo_ctrl::EcatGetVer&) { return value(); }
};


// service_traits::MD5Sum< ::servo_ctrl::EcatGetVerRequest> should match
// service_traits::MD5Sum< ::servo_ctrl::EcatGetVer >
template<>
struct MD5Sum< ::servo_ctrl::EcatGetVerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::servo_ctrl::EcatGetVer >::value();
  }
  static const char* value(const ::servo_ctrl::EcatGetVerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::servo_ctrl::EcatGetVerRequest> should match
// service_traits::DataType< ::servo_ctrl::EcatGetVer >
template<>
struct DataType< ::servo_ctrl::EcatGetVerRequest>
{
  static const char* value()
  {
    return DataType< ::servo_ctrl::EcatGetVer >::value();
  }
  static const char* value(const ::servo_ctrl::EcatGetVerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::servo_ctrl::EcatGetVerResponse> should match
// service_traits::MD5Sum< ::servo_ctrl::EcatGetVer >
template<>
struct MD5Sum< ::servo_ctrl::EcatGetVerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::servo_ctrl::EcatGetVer >::value();
  }
  static const char* value(const ::servo_ctrl::EcatGetVerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::servo_ctrl::EcatGetVerResponse> should match
// service_traits::DataType< ::servo_ctrl::EcatGetVer >
template<>
struct DataType< ::servo_ctrl::EcatGetVerResponse>
{
  static const char* value()
  {
    return DataType< ::servo_ctrl::EcatGetVer >::value();
  }
  static const char* value(const ::servo_ctrl::EcatGetVerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVO_CTRL_MESSAGE_ECATGETVER_H
