// Generated by gencpp from file cruiser_msgs/ChassisCommandResponse.msg
// DO NOT EDIT!


#ifndef CRUISER_MSGS_MESSAGE_CHASSISCOMMANDRESPONSE_H
#define CRUISER_MSGS_MESSAGE_CHASSISCOMMANDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cruiser_msgs
{
template <class ContainerAllocator>
struct ChassisCommandResponse_
{
  typedef ChassisCommandResponse_<ContainerAllocator> Type;

  ChassisCommandResponse_()
    : time(0)  {
    }
  ChassisCommandResponse_(const ContainerAllocator& _alloc)
    : time(0)  {
  (void)_alloc;
    }



   typedef uint32_t _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ChassisCommandResponse_

typedef ::cruiser_msgs::ChassisCommandResponse_<std::allocator<void> > ChassisCommandResponse;

typedef boost::shared_ptr< ::cruiser_msgs::ChassisCommandResponse > ChassisCommandResponsePtr;
typedef boost::shared_ptr< ::cruiser_msgs::ChassisCommandResponse const> ChassisCommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator1> & lhs, const ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator2> & rhs)
{
  return lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator1> & lhs, const ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cruiser_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d16de83ef4e326bbfdc1e90377f0a2c6";
  }

  static const char* value(const ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd16de83ef4e326bbULL;
  static const uint64_t static_value2 = 0xfdc1e90377f0a2c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cruiser_msgs/ChassisCommandResponse";
  }

  static const char* value(const ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# time in millisecond. 1000 stands for 1s\n"
"uint32 time\n"
"\n"
;
  }

  static const char* value(const ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChassisCommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cruiser_msgs::ChassisCommandResponse_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRUISER_MSGS_MESSAGE_CHASSISCOMMANDRESPONSE_H
