// Generated by gencpp from file cruiser_msgs/GetMapJson.msg
// DO NOT EDIT!


#ifndef CRUISER_MSGS_MESSAGE_GETMAPJSON_H
#define CRUISER_MSGS_MESSAGE_GETMAPJSON_H

#include <ros/service_traits.h>


#include <cruiser_msgs/GetMapJsonRequest.h>
#include <cruiser_msgs/GetMapJsonResponse.h>


namespace cruiser_msgs
{

struct GetMapJson
{

typedef GetMapJsonRequest Request;
typedef GetMapJsonResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMapJson
} // namespace cruiser_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cruiser_msgs::GetMapJson > {
  static const char* value()
  {
    return "6825166e7da48608dd55394f68c70e3e";
  }

  static const char* value(const ::cruiser_msgs::GetMapJson&) { return value(); }
};

template<>
struct DataType< ::cruiser_msgs::GetMapJson > {
  static const char* value()
  {
    return "cruiser_msgs/GetMapJson";
  }

  static const char* value(const ::cruiser_msgs::GetMapJson&) { return value(); }
};


// service_traits::MD5Sum< ::cruiser_msgs::GetMapJsonRequest> should match
// service_traits::MD5Sum< ::cruiser_msgs::GetMapJson >
template<>
struct MD5Sum< ::cruiser_msgs::GetMapJsonRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cruiser_msgs::GetMapJson >::value();
  }
  static const char* value(const ::cruiser_msgs::GetMapJsonRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cruiser_msgs::GetMapJsonRequest> should match
// service_traits::DataType< ::cruiser_msgs::GetMapJson >
template<>
struct DataType< ::cruiser_msgs::GetMapJsonRequest>
{
  static const char* value()
  {
    return DataType< ::cruiser_msgs::GetMapJson >::value();
  }
  static const char* value(const ::cruiser_msgs::GetMapJsonRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cruiser_msgs::GetMapJsonResponse> should match
// service_traits::MD5Sum< ::cruiser_msgs::GetMapJson >
template<>
struct MD5Sum< ::cruiser_msgs::GetMapJsonResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cruiser_msgs::GetMapJson >::value();
  }
  static const char* value(const ::cruiser_msgs::GetMapJsonResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cruiser_msgs::GetMapJsonResponse> should match
// service_traits::DataType< ::cruiser_msgs::GetMapJson >
template<>
struct DataType< ::cruiser_msgs::GetMapJsonResponse>
{
  static const char* value()
  {
    return DataType< ::cruiser_msgs::GetMapJson >::value();
  }
  static const char* value(const ::cruiser_msgs::GetMapJsonResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRUISER_MSGS_MESSAGE_GETMAPJSON_H
