// Generated by gencpp from file cruiser_msgs/VirtualWall.msg
// DO NOT EDIT!


#ifndef CRUISER_MSGS_MESSAGE_VIRTUALWALL_H
#define CRUISER_MSGS_MESSAGE_VIRTUALWALL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/MapMetaData.h>
#include <nav_msgs/Path.h>

namespace cruiser_msgs
{
template <class ContainerAllocator>
struct VirtualWall_
{
  typedef VirtualWall_<ContainerAllocator> Type;

  VirtualWall_()
    : info()
    , walls()  {
    }
  VirtualWall_(const ContainerAllocator& _alloc)
    : info(_alloc)
    , walls(_alloc)  {
  (void)_alloc;
    }



   typedef  ::nav_msgs::MapMetaData_<ContainerAllocator>  _info_type;
  _info_type info;

   typedef std::vector< ::nav_msgs::Path_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::nav_msgs::Path_<ContainerAllocator> >::other >  _walls_type;
  _walls_type walls;





  typedef boost::shared_ptr< ::cruiser_msgs::VirtualWall_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cruiser_msgs::VirtualWall_<ContainerAllocator> const> ConstPtr;

}; // struct VirtualWall_

typedef ::cruiser_msgs::VirtualWall_<std::allocator<void> > VirtualWall;

typedef boost::shared_ptr< ::cruiser_msgs::VirtualWall > VirtualWallPtr;
typedef boost::shared_ptr< ::cruiser_msgs::VirtualWall const> VirtualWallConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cruiser_msgs::VirtualWall_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cruiser_msgs::VirtualWall_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cruiser_msgs::VirtualWall_<ContainerAllocator1> & lhs, const ::cruiser_msgs::VirtualWall_<ContainerAllocator2> & rhs)
{
  return lhs.info == rhs.info &&
    lhs.walls == rhs.walls;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cruiser_msgs::VirtualWall_<ContainerAllocator1> & lhs, const ::cruiser_msgs::VirtualWall_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cruiser_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cruiser_msgs::VirtualWall_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cruiser_msgs::VirtualWall_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cruiser_msgs::VirtualWall_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cruiser_msgs::VirtualWall_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cruiser_msgs::VirtualWall_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cruiser_msgs::VirtualWall_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cruiser_msgs::VirtualWall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f2a170bcae45cdc4c5d5fe2965ae941e";
  }

  static const char* value(const ::cruiser_msgs::VirtualWall_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf2a170bcae45cdc4ULL;
  static const uint64_t static_value2 = 0xc5d5fe2965ae941eULL;
};

template<class ContainerAllocator>
struct DataType< ::cruiser_msgs::VirtualWall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cruiser_msgs/VirtualWall";
  }

  static const char* value(const ::cruiser_msgs::VirtualWall_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cruiser_msgs::VirtualWall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_msgs/MapMetaData info\n"
"nav_msgs/Path[] walls\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/MapMetaData\n"
"# This hold basic information about the characterists of the OccupancyGrid\n"
"\n"
"# The time at which the map was loaded\n"
"time map_load_time\n"
"# The map resolution [m/cell]\n"
"float32 resolution\n"
"# Map width [cells]\n"
"uint32 width\n"
"# Map height [cells]\n"
"uint32 height\n"
"# The origin of the map [m, m, rad].  This is the real-world pose of the\n"
"# cell (0,0) in the map.\n"
"geometry_msgs/Pose origin\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
;
  }

  static const char* value(const ::cruiser_msgs::VirtualWall_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cruiser_msgs::VirtualWall_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.info);
      stream.next(m.walls);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VirtualWall_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cruiser_msgs::VirtualWall_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cruiser_msgs::VirtualWall_<ContainerAllocator>& v)
  {
    s << indent << "info: ";
    s << std::endl;
    Printer< ::nav_msgs::MapMetaData_<ContainerAllocator> >::stream(s, indent + "  ", v.info);
    s << indent << "walls[]" << std::endl;
    for (size_t i = 0; i < v.walls.size(); ++i)
    {
      s << indent << "  walls[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "    ", v.walls[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRUISER_MSGS_MESSAGE_VIRTUALWALL_H
