// Generated by gencpp from file servo_ctrl/SetBasePowerResponse.msg
// DO NOT EDIT!


#ifndef SERVO_CTRL_MESSAGE_SETBASEPOWERRESPONSE_H
#define SERVO_CTRL_MESSAGE_SETBASEPOWERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servo_ctrl
{
template <class ContainerAllocator>
struct SetBasePowerResponse_
{
  typedef SetBasePowerResponse_<ContainerAllocator> Type;

  SetBasePowerResponse_()
    : result()  {
    }
  SetBasePowerResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::servo_ctrl::SetBasePowerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servo_ctrl::SetBasePowerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetBasePowerResponse_

typedef ::servo_ctrl::SetBasePowerResponse_<std::allocator<void> > SetBasePowerResponse;

typedef boost::shared_ptr< ::servo_ctrl::SetBasePowerResponse > SetBasePowerResponsePtr;
typedef boost::shared_ptr< ::servo_ctrl::SetBasePowerResponse const> SetBasePowerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servo_ctrl::SetBasePowerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servo_ctrl::SetBasePowerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace servo_ctrl

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::servo_ctrl::SetBasePowerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_ctrl::SetBasePowerResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_ctrl::SetBasePowerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_ctrl::SetBasePowerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_ctrl::SetBasePowerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_ctrl::SetBasePowerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servo_ctrl::SetBasePowerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7ed20811caa3db643b4512e66e3f767";
  }

  static const char* value(const ::servo_ctrl::SetBasePowerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7ed20811caa3db6ULL;
  static const uint64_t static_value2 = 0x43b4512e66e3f767ULL;
};

template<class ContainerAllocator>
struct DataType< ::servo_ctrl::SetBasePowerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servo_ctrl/SetBasePowerResponse";
  }

  static const char* value(const ::servo_ctrl::SetBasePowerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servo_ctrl::SetBasePowerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] result\n\
\n\
";
  }

  static const char* value(const ::servo_ctrl::SetBasePowerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servo_ctrl::SetBasePowerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetBasePowerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servo_ctrl::SetBasePowerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servo_ctrl::SetBasePowerResponse_<ContainerAllocator>& v)
  {
    s << indent << "result[]" << std::endl;
    for (size_t i = 0; i < v.result.size(); ++i)
    {
      s << indent << "  result[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.result[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVO_CTRL_MESSAGE_SETBASEPOWERRESPONSE_H
