// Generated by gencpp from file broadcast_teleop/TaskCallScript.msg
// DO NOT EDIT!


#ifndef BROADCAST_TELEOP_MESSAGE_TASKCALLSCRIPT_H
#define BROADCAST_TELEOP_MESSAGE_TASKCALLSCRIPT_H

#include <ros/service_traits.h>


#include <broadcast_teleop/TaskCallScriptRequest.h>
#include <broadcast_teleop/TaskCallScriptResponse.h>


namespace broadcast_teleop
{

struct TaskCallScript
{

typedef TaskCallScriptRequest Request;
typedef TaskCallScriptResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TaskCallScript
} // namespace broadcast_teleop


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::broadcast_teleop::TaskCallScript > {
  static const char* value()
  {
    return "d091270bbc490f371f9855f018f74a07";
  }

  static const char* value(const ::broadcast_teleop::TaskCallScript&) { return value(); }
};

template<>
struct DataType< ::broadcast_teleop::TaskCallScript > {
  static const char* value()
  {
    return "broadcast_teleop/TaskCallScript";
  }

  static const char* value(const ::broadcast_teleop::TaskCallScript&) { return value(); }
};


// service_traits::MD5Sum< ::broadcast_teleop::TaskCallScriptRequest> should match
// service_traits::MD5Sum< ::broadcast_teleop::TaskCallScript >
template<>
struct MD5Sum< ::broadcast_teleop::TaskCallScriptRequest>
{
  static const char* value()
  {
    return MD5Sum< ::broadcast_teleop::TaskCallScript >::value();
  }
  static const char* value(const ::broadcast_teleop::TaskCallScriptRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::broadcast_teleop::TaskCallScriptRequest> should match
// service_traits::DataType< ::broadcast_teleop::TaskCallScript >
template<>
struct DataType< ::broadcast_teleop::TaskCallScriptRequest>
{
  static const char* value()
  {
    return DataType< ::broadcast_teleop::TaskCallScript >::value();
  }
  static const char* value(const ::broadcast_teleop::TaskCallScriptRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::broadcast_teleop::TaskCallScriptResponse> should match
// service_traits::MD5Sum< ::broadcast_teleop::TaskCallScript >
template<>
struct MD5Sum< ::broadcast_teleop::TaskCallScriptResponse>
{
  static const char* value()
  {
    return MD5Sum< ::broadcast_teleop::TaskCallScript >::value();
  }
  static const char* value(const ::broadcast_teleop::TaskCallScriptResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::broadcast_teleop::TaskCallScriptResponse> should match
// service_traits::DataType< ::broadcast_teleop::TaskCallScript >
template<>
struct DataType< ::broadcast_teleop::TaskCallScriptResponse>
{
  static const char* value()
  {
    return DataType< ::broadcast_teleop::TaskCallScript >::value();
  }
  static const char* value(const ::broadcast_teleop::TaskCallScriptResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BROADCAST_TELEOP_MESSAGE_TASKCALLSCRIPT_H
