# functions
string FUNC_DYNAMIC=dynamic
string FUNC_BALANCE=balance
string FUNC_COMPLIANCE=compliance
string FUNC_TAICHI=taichi
string FUNC_YOGA=yoga
string FUNC_JUMP=jump

# command
string CMD_START=start
string CMD_STOP=stop

# members
string func_name
string param_json # json format parameters
string cmd
---
bool success
string message
