(cl:defpackage serial_device-srv
  (:use )
  (:export
   "TASKCALLSERIAL"
   "<TASKCALLSERIAL-REQUEST>"
   "TASKCALLSERIAL-REQUEST"
   "<TASKCALLSERIAL-RESPONSE>"
   "TASKCALLSERIAL-RESPONSE"
   "TASKSERVICE"
   "<TASKSERVICE-REQUEST>"
   "TASKSERVICE-REQUEST"
   "<TASKSERVICE-RESPONSE>"
   "TASKSERVICE-RESPONSE"
  ))

