// Generated by gencpp from file ubt_core_msgs/OpenCameraRequest.msg
// DO NOT EDIT!


#ifndef UBT_CORE_MSGS_MESSAGE_OPENCAMERAREQUEST_H
#define UBT_CORE_MSGS_MESSAGE_OPENCAMERAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ubt_core_msgs/CameraSettings.h>

namespace ubt_core_msgs
{
template <class ContainerAllocator>
struct OpenCameraRequest_
{
  typedef OpenCameraRequest_<ContainerAllocator> Type;

  OpenCameraRequest_()
    : name()
    , settings()  {
    }
  OpenCameraRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , settings(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef  ::ubt_core_msgs::CameraSettings_<ContainerAllocator>  _settings_type;
  _settings_type settings;





  typedef boost::shared_ptr< ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator> const> ConstPtr;

}; // struct OpenCameraRequest_

typedef ::ubt_core_msgs::OpenCameraRequest_<std::allocator<void> > OpenCameraRequest;

typedef boost::shared_ptr< ::ubt_core_msgs::OpenCameraRequest > OpenCameraRequestPtr;
typedef boost::shared_ptr< ::ubt_core_msgs::OpenCameraRequest const> OpenCameraRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator1> & lhs, const ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.settings == rhs.settings;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator1> & lhs, const ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ubt_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4194eee32741c5a98ef8da9666fa6c9";
  }

  static const char* value(const ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4194eee32741c5aULL;
  static const uint64_t static_value2 = 0x98ef8da9666fa6c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ubt_core_msgs/OpenCameraRequest";
  }

  static const char* value(const ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string          name\n"
"CameraSettings  settings\n"
"\n"
"================================================================================\n"
"MSG: ubt_core_msgs/CameraSettings\n"
"int32           width\n"
"int32           height\n"
"float32         fps\n"
"CameraControl[] controls\n"
"\n"
"================================================================================\n"
"MSG: ubt_core_msgs/CameraControl\n"
"int32   id\n"
"int32   value\n"
"\n"
"int32 CAMERA_CONTROL_EXPOSURE=100\n"
"int32 CAMERA_CONTROL_GAIN=101\n"
"int32 CAMERA_CONTROL_WHITE_BALANCE_R=102\n"
"int32 CAMERA_CONTROL_WHITE_BALANCE_G=103\n"
"int32 CAMERA_CONTROL_WHITE_BALANCE_B=104\n"
"int32 CAMERA_CONTROL_WINDOW_X=105\n"
"int32 CAMERA_CONTROL_WINDOW_Y=106\n"
"int32 CAMERA_CONTROL_FLIP=107\n"
"int32 CAMERA_CONTROL_MIRROR=108\n"
"int32 CAMERA_CONTROL_RESOLUTION_HALF=109\n"
;
  }

  static const char* value(const ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.settings);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OpenCameraRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ubt_core_msgs::OpenCameraRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "settings: ";
    s << std::endl;
    Printer< ::ubt_core_msgs::CameraSettings_<ContainerAllocator> >::stream(s, indent + "  ", v.settings);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UBT_CORE_MSGS_MESSAGE_OPENCAMERAREQUEST_H
