# cmd: "get", "set"
string cmd

# servo(case insensitive): LHipYaw,LHipRoll,LHipPitch,LKneePitch,LAnklePitch,LAnkleRoll,RHipYaw,RHipRoll,RHipPitch,RKneePitch,RAnklePitch,RAnkleRoll
string servo

# mode: pos, vel, trq
string mode

# pid
int16 kp
int16 ki
int16 kd
---
int16 kp
int16 ki
int16 kd
