// Generated by gencpp from file servo_ctrl/EcatGetPVT.msg
// DO NOT EDIT!


#ifndef SERVO_CTRL_MESSAGE_ECATGETPVT_H
#define SERVO_CTRL_MESSAGE_ECATGETPVT_H

#include <ros/service_traits.h>


#include <servo_ctrl/EcatGetPVTRequest.h>
#include <servo_ctrl/EcatGetPVTResponse.h>


namespace servo_ctrl
{

struct EcatGetPVT
{

typedef EcatGetPVTRequest Request;
typedef EcatGetPVTResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EcatGetPVT
} // namespace servo_ctrl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::servo_ctrl::EcatGetPVT > {
  static const char* value()
  {
    return "c489f93ef6aafee9eaeb152fcdcb6ab1";
  }

  static const char* value(const ::servo_ctrl::EcatGetPVT&) { return value(); }
};

template<>
struct DataType< ::servo_ctrl::EcatGetPVT > {
  static const char* value()
  {
    return "servo_ctrl/EcatGetPVT";
  }

  static const char* value(const ::servo_ctrl::EcatGetPVT&) { return value(); }
};


// service_traits::MD5Sum< ::servo_ctrl::EcatGetPVTRequest> should match 
// service_traits::MD5Sum< ::servo_ctrl::EcatGetPVT > 
template<>
struct MD5Sum< ::servo_ctrl::EcatGetPVTRequest>
{
  static const char* value()
  {
    return MD5Sum< ::servo_ctrl::EcatGetPVT >::value();
  }
  static const char* value(const ::servo_ctrl::EcatGetPVTRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::servo_ctrl::EcatGetPVTRequest> should match 
// service_traits::DataType< ::servo_ctrl::EcatGetPVT > 
template<>
struct DataType< ::servo_ctrl::EcatGetPVTRequest>
{
  static const char* value()
  {
    return DataType< ::servo_ctrl::EcatGetPVT >::value();
  }
  static const char* value(const ::servo_ctrl::EcatGetPVTRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::servo_ctrl::EcatGetPVTResponse> should match 
// service_traits::MD5Sum< ::servo_ctrl::EcatGetPVT > 
template<>
struct MD5Sum< ::servo_ctrl::EcatGetPVTResponse>
{
  static const char* value()
  {
    return MD5Sum< ::servo_ctrl::EcatGetPVT >::value();
  }
  static const char* value(const ::servo_ctrl::EcatGetPVTResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::servo_ctrl::EcatGetPVTResponse> should match 
// service_traits::DataType< ::servo_ctrl::EcatGetPVT > 
template<>
struct DataType< ::servo_ctrl::EcatGetPVTResponse>
{
  static const char* value()
  {
    return DataType< ::servo_ctrl::EcatGetPVT >::value();
  }
  static const char* value(const ::servo_ctrl::EcatGetPVTResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVO_CTRL_MESSAGE_ECATGETPVT_H
