// Generated by gencpp from file servo_ctrl/SetBasePower.msg
// DO NOT EDIT!


#ifndef SERVO_CTRL_MESSAGE_SETBASEPOWER_H
#define SERVO_CTRL_MESSAGE_SETBASEPOWER_H

#include <ros/service_traits.h>


#include <servo_ctrl/SetBasePowerRequest.h>
#include <servo_ctrl/SetBasePowerResponse.h>


namespace servo_ctrl
{

struct SetBasePower
{

typedef SetBasePowerRequest Request;
typedef SetBasePowerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetBasePower
} // namespace servo_ctrl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::servo_ctrl::SetBasePower > {
  static const char* value()
  {
    return "b0bc70d7e1fded55183cc6d4deee36a2";
  }

  static const char* value(const ::servo_ctrl::SetBasePower&) { return value(); }
};

template<>
struct DataType< ::servo_ctrl::SetBasePower > {
  static const char* value()
  {
    return "servo_ctrl/SetBasePower";
  }

  static const char* value(const ::servo_ctrl::SetBasePower&) { return value(); }
};


// service_traits::MD5Sum< ::servo_ctrl::SetBasePowerRequest> should match 
// service_traits::MD5Sum< ::servo_ctrl::SetBasePower > 
template<>
struct MD5Sum< ::servo_ctrl::SetBasePowerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::servo_ctrl::SetBasePower >::value();
  }
  static const char* value(const ::servo_ctrl::SetBasePowerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::servo_ctrl::SetBasePowerRequest> should match 
// service_traits::DataType< ::servo_ctrl::SetBasePower > 
template<>
struct DataType< ::servo_ctrl::SetBasePowerRequest>
{
  static const char* value()
  {
    return DataType< ::servo_ctrl::SetBasePower >::value();
  }
  static const char* value(const ::servo_ctrl::SetBasePowerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::servo_ctrl::SetBasePowerResponse> should match 
// service_traits::MD5Sum< ::servo_ctrl::SetBasePower > 
template<>
struct MD5Sum< ::servo_ctrl::SetBasePowerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::servo_ctrl::SetBasePower >::value();
  }
  static const char* value(const ::servo_ctrl::SetBasePowerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::servo_ctrl::SetBasePowerResponse> should match 
// service_traits::DataType< ::servo_ctrl::SetBasePower > 
template<>
struct DataType< ::servo_ctrl::SetBasePowerResponse>
{
  static const char* value()
  {
    return DataType< ::servo_ctrl::SetBasePower >::value();
  }
  static const char* value(const ::servo_ctrl::SetBasePowerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVO_CTRL_MESSAGE_SETBASEPOWER_H
