// Generated by gencpp from file cruiser_msgs/GetUwbSupportedMode.msg
// DO NOT EDIT!


#ifndef CRUISER_MSGS_MESSAGE_GETUWBSUPPORTEDMODE_H
#define CRUISER_MSGS_MESSAGE_GETUWBSUPPORTEDMODE_H

#include <ros/service_traits.h>


#include <cruiser_msgs/GetUwbSupportedModeRequest.h>
#include <cruiser_msgs/GetUwbSupportedModeResponse.h>


namespace cruiser_msgs
{

struct GetUwbSupportedMode
{

typedef GetUwbSupportedModeRequest Request;
typedef GetUwbSupportedModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetUwbSupportedMode
} // namespace cruiser_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cruiser_msgs::GetUwbSupportedMode > {
  static const char* value()
  {
    return "3c35866e3d60aa551b5343ed0f3e9138";
  }

  static const char* value(const ::cruiser_msgs::GetUwbSupportedMode&) { return value(); }
};

template<>
struct DataType< ::cruiser_msgs::GetUwbSupportedMode > {
  static const char* value()
  {
    return "cruiser_msgs/GetUwbSupportedMode";
  }

  static const char* value(const ::cruiser_msgs::GetUwbSupportedMode&) { return value(); }
};


// service_traits::MD5Sum< ::cruiser_msgs::GetUwbSupportedModeRequest> should match
// service_traits::MD5Sum< ::cruiser_msgs::GetUwbSupportedMode >
template<>
struct MD5Sum< ::cruiser_msgs::GetUwbSupportedModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cruiser_msgs::GetUwbSupportedMode >::value();
  }
  static const char* value(const ::cruiser_msgs::GetUwbSupportedModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cruiser_msgs::GetUwbSupportedModeRequest> should match
// service_traits::DataType< ::cruiser_msgs::GetUwbSupportedMode >
template<>
struct DataType< ::cruiser_msgs::GetUwbSupportedModeRequest>
{
  static const char* value()
  {
    return DataType< ::cruiser_msgs::GetUwbSupportedMode >::value();
  }
  static const char* value(const ::cruiser_msgs::GetUwbSupportedModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cruiser_msgs::GetUwbSupportedModeResponse> should match
// service_traits::MD5Sum< ::cruiser_msgs::GetUwbSupportedMode >
template<>
struct MD5Sum< ::cruiser_msgs::GetUwbSupportedModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cruiser_msgs::GetUwbSupportedMode >::value();
  }
  static const char* value(const ::cruiser_msgs::GetUwbSupportedModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cruiser_msgs::GetUwbSupportedModeResponse> should match
// service_traits::DataType< ::cruiser_msgs::GetUwbSupportedMode >
template<>
struct DataType< ::cruiser_msgs::GetUwbSupportedModeResponse>
{
  static const char* value()
  {
    return DataType< ::cruiser_msgs::GetUwbSupportedMode >::value();
  }
  static const char* value(const ::cruiser_msgs::GetUwbSupportedModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRUISER_MSGS_MESSAGE_GETUWBSUPPORTEDMODE_H
