// Generated by gencpp from file cruiser_msgs/ObstacleStatus.msg
// DO NOT EDIT!


#ifndef CRUISER_MSGS_MESSAGE_OBSTACLESTATUS_H
#define CRUISER_MSGS_MESSAGE_OBSTACLESTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>

namespace cruiser_msgs
{
template <class ContainerAllocator>
struct ObstacleStatus_
{
  typedef ObstacleStatus_<ContainerAllocator> Type;

  ObstacleStatus_()
    : lethal_dis(0.0)
    , inflated_dis(0.0)
    , lethal_pose()
    , inflated_pose()  {
    }
  ObstacleStatus_(const ContainerAllocator& _alloc)
    : lethal_dis(0.0)
    , inflated_dis(0.0)
    , lethal_pose(_alloc)
    , inflated_pose(_alloc)  {
  (void)_alloc;
    }



   typedef float _lethal_dis_type;
  _lethal_dis_type lethal_dis;

   typedef float _inflated_dis_type;
  _inflated_dis_type inflated_dis;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _lethal_pose_type;
  _lethal_pose_type lethal_pose;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _inflated_pose_type;
  _inflated_pose_type inflated_pose;





  typedef boost::shared_ptr< ::cruiser_msgs::ObstacleStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cruiser_msgs::ObstacleStatus_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleStatus_

typedef ::cruiser_msgs::ObstacleStatus_<std::allocator<void> > ObstacleStatus;

typedef boost::shared_ptr< ::cruiser_msgs::ObstacleStatus > ObstacleStatusPtr;
typedef boost::shared_ptr< ::cruiser_msgs::ObstacleStatus const> ObstacleStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cruiser_msgs::ObstacleStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cruiser_msgs::ObstacleStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cruiser_msgs::ObstacleStatus_<ContainerAllocator1> & lhs, const ::cruiser_msgs::ObstacleStatus_<ContainerAllocator2> & rhs)
{
  return lhs.lethal_dis == rhs.lethal_dis &&
    lhs.inflated_dis == rhs.inflated_dis &&
    lhs.lethal_pose == rhs.lethal_pose &&
    lhs.inflated_pose == rhs.inflated_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cruiser_msgs::ObstacleStatus_<ContainerAllocator1> & lhs, const ::cruiser_msgs::ObstacleStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cruiser_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cruiser_msgs::ObstacleStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cruiser_msgs::ObstacleStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cruiser_msgs::ObstacleStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cruiser_msgs::ObstacleStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cruiser_msgs::ObstacleStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cruiser_msgs::ObstacleStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cruiser_msgs::ObstacleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e84b2031a914018d70a2626de80e5ca";
  }

  static const char* value(const ::cruiser_msgs::ObstacleStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e84b2031a914018ULL;
  static const uint64_t static_value2 = 0xd70a2626de80e5caULL;
};

template<class ContainerAllocator>
struct DataType< ::cruiser_msgs::ObstacleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cruiser_msgs/ObstacleStatus";
  }

  static const char* value(const ::cruiser_msgs::ObstacleStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cruiser_msgs::ObstacleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 lethal_dis\n"
"float32 inflated_dis\n"
"geometry_msgs/PoseStamped lethal_pose\n"
"geometry_msgs/PoseStamped inflated_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::cruiser_msgs::ObstacleStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cruiser_msgs::ObstacleStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lethal_dis);
      stream.next(m.inflated_dis);
      stream.next(m.lethal_pose);
      stream.next(m.inflated_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cruiser_msgs::ObstacleStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cruiser_msgs::ObstacleStatus_<ContainerAllocator>& v)
  {
    s << indent << "lethal_dis: ";
    Printer<float>::stream(s, indent + "  ", v.lethal_dis);
    s << indent << "inflated_dis: ";
    Printer<float>::stream(s, indent + "  ", v.inflated_dis);
    s << indent << "lethal_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.lethal_pose);
    s << indent << "inflated_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.inflated_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRUISER_MSGS_MESSAGE_OBSTACLESTATUS_H
