# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cruiser_msgs/geomagnetism.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class geomagnetism(genpy.Message):
  _md5sum = "a11ec4346fd95eab51cf9d95e5a6dc16"
  _type = "cruiser_msgs/geomagnetism"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 gyro_x
int32 gyro_y
int32 gyro_z
int32 acc_x
int32 acc_y
int32 acc_z
int32 magnetic_x
int32 magnetic_y
int32 magnetic_z
int32 euler_pitch
int32 euler_roll
int32 euler_yaw
bool trigger




"""
  __slots__ = ['gyro_x','gyro_y','gyro_z','acc_x','acc_y','acc_z','magnetic_x','magnetic_y','magnetic_z','euler_pitch','euler_roll','euler_yaw','trigger']
  _slot_types = ['int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       gyro_x,gyro_y,gyro_z,acc_x,acc_y,acc_z,magnetic_x,magnetic_y,magnetic_z,euler_pitch,euler_roll,euler_yaw,trigger

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(geomagnetism, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.gyro_x is None:
        self.gyro_x = 0
      if self.gyro_y is None:
        self.gyro_y = 0
      if self.gyro_z is None:
        self.gyro_z = 0
      if self.acc_x is None:
        self.acc_x = 0
      if self.acc_y is None:
        self.acc_y = 0
      if self.acc_z is None:
        self.acc_z = 0
      if self.magnetic_x is None:
        self.magnetic_x = 0
      if self.magnetic_y is None:
        self.magnetic_y = 0
      if self.magnetic_z is None:
        self.magnetic_z = 0
      if self.euler_pitch is None:
        self.euler_pitch = 0
      if self.euler_roll is None:
        self.euler_roll = 0
      if self.euler_yaw is None:
        self.euler_yaw = 0
      if self.trigger is None:
        self.trigger = False
    else:
      self.gyro_x = 0
      self.gyro_y = 0
      self.gyro_z = 0
      self.acc_x = 0
      self.acc_y = 0
      self.acc_z = 0
      self.magnetic_x = 0
      self.magnetic_y = 0
      self.magnetic_z = 0
      self.euler_pitch = 0
      self.euler_roll = 0
      self.euler_yaw = 0
      self.trigger = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_12iB().pack(_x.gyro_x, _x.gyro_y, _x.gyro_z, _x.acc_x, _x.acc_y, _x.acc_z, _x.magnetic_x, _x.magnetic_y, _x.magnetic_z, _x.euler_pitch, _x.euler_roll, _x.euler_yaw, _x.trigger))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 49
      (_x.gyro_x, _x.gyro_y, _x.gyro_z, _x.acc_x, _x.acc_y, _x.acc_z, _x.magnetic_x, _x.magnetic_y, _x.magnetic_z, _x.euler_pitch, _x.euler_roll, _x.euler_yaw, _x.trigger,) = _get_struct_12iB().unpack(str[start:end])
      self.trigger = bool(self.trigger)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_12iB().pack(_x.gyro_x, _x.gyro_y, _x.gyro_z, _x.acc_x, _x.acc_y, _x.acc_z, _x.magnetic_x, _x.magnetic_y, _x.magnetic_z, _x.euler_pitch, _x.euler_roll, _x.euler_yaw, _x.trigger))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 49
      (_x.gyro_x, _x.gyro_y, _x.gyro_z, _x.acc_x, _x.acc_y, _x.acc_z, _x.magnetic_x, _x.magnetic_y, _x.magnetic_z, _x.euler_pitch, _x.euler_roll, _x.euler_yaw, _x.trigger,) = _get_struct_12iB().unpack(str[start:end])
      self.trigger = bool(self.trigger)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12iB = None
def _get_struct_12iB():
    global _struct_12iB
    if _struct_12iB is None:
        _struct_12iB = struct.Struct("<12iB")
    return _struct_12iB
